# ──────────────────────────────────────────────────────────────────────────────
# PROFILE: local (Desenvolvimento)
# ──────────────────────────────────────────────────────────────────────────────

# Configurações do Banco de Dados Local
spring.datasource.url=jdbc:mysql://localhost:3306/{nome do banco de dados}
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate (Localmente é útil ver o SQL)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# JWT (Chave de teste local)
# JWT (Chave de teste local - 512 bits)
jwt.secret=404e635266556a586e3272357538782f413f4428472b4b6250645367566b5970337336763979244226452948404d635166546a576e5a7134743777217a25432a
jwt.expiration=86400000

# Servidor e CORS
server.port=8080
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173

# Email (Desabilitado ou usando chave fake)
sendgrid.api.key=OFF
sendgrid.from.email=teste@local.com